route:
  repeat_interval: 15s # Time interval between consecutive notifications for the same alert
  receiver: discord

receivers:
- name: discord
  discord_configs:
  - webhook_url: https://discord.com/api/webhooks/1217694181556752395/40CUPhNzO88m6Gd549VJYukZp06gRh1c5gA5lrjFM5k2_LnwNj-PW2FMgOvVAIiqOoQx
