apiVersion: v1
kind: Service
metadata:
  name: {{ include "ic-app.fullname" . }}
  labels:
    {{- include "ic-app.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      name: {{ .name }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
    {{- end}}
  selector:
    {{- include "ic-app.selectorLabels" . | nindent 4 }}
